image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2
  GOPATH: $CI_PROJECT_DIR/../gopath

stages:
  - build
  - publish

before_script:
  - docker info
  - mkdir -p $GOPATH
  - apk update
  - apk add git go-tools make lftp
  - go env

.build:
  script:
    - make pull
    - make $PLATFORM

.publish:
  script:
    - make pull
    - make $PLATFORM
  after_script:
    - |
        mkdir -p build
        lftp -c "open 'ftp://$FTP_USER:$FTP_PASS@$FTP_HOST'; \
        mkdir -p -f elementum-binaries/$CI_BUILD_REF_NAME; \
        lcd build; \
        cd elementum-binaries/$CI_BUILD_REF_NAME; \
        mirror --reverse --verbose --include-glob *; \
        exit;"
  only:
    - tags
    - master

.parallel-matrix:
  parallel:
    matrix:
      - PLATFORM: 
        - android-arm
        - android-arm-shared
        - android-arm64
        - android-arm64-shared
        - android-x64
        - android-x64-shared
        - android-x86
        - android-x86-shared
        - linux-armv6
        - linux-armv6-shared
        - linux-armv7
        - linux-armv7-shared
        - linux-armv7_softfp
        - linux-armv7_softfp-shared
        - linux-arm64
        - linux-arm64-shared
        - linux-x64
        - linux-x64-shared
        - linux-x86
        - linux-x86-shared
        - windows-x64
        - windows-x64-shared
        - windows-x86
        - windows-x86-shared
        - darwin-x64
        - darwin-x64-shared

build:
  stage: build
  extends: 
    - .parallel-matrix 
    - .build
  artifacts:
    paths:
      - "build/**"

publish:
  stage: publish
  extends: 
    - .parallel-matrix 
    - .publish
