name: cover 100%
on: [push]
jobs:

  # Verify minimum coverage is reached using `go test -short -cover` on latest-ubuntu with default version of Go.
  # The grep expression can't be too strict, it needed to be relaxed to work with different versions of Go.
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      #uses: actions/checkout@v1
    - name: Go Coverage
      run: |
        make pull-all
        export GOPATH="~/go"
        make libs
        go version
        go get github.com/mattn/go-isatty
        go get github.com/I-Cat/elementum/tree/master
        go get github.com/I-Cat/elementum/tree/CustomPieceCompletion
        go get github.com/I-Cat/elementum/tree/mk
        make linux-x64
        make darwin-x64
        make windows-x86
        go get updates
        go push github.com/I-Cat/go
        go test -short -cover | grep "^.*coverage:.*of statements$" | python -c "import os,re,sys; cover_rpt = sys.stdin.read(); print(cover_rpt) if len(cover_rpt) != 0 and len(cover_rpt.splitlines()) == 1 else sys.exit(1); min_cover = float(re.findall(r'\d*\.\d+|\d+', os.environ['GITHUB_WORKFLOW'])[0]); cover = float(re.findall(r'\d*\.\d+|\d+', cover_rpt)[0]); sys.exit(1) if (cover > 100) or (cover < min_cover) else sys.exit(0)"
      #stop      
      shell: bash
