# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+ uses: actions/checkout@v1
uses: actions/checkout@v2
make: actions/setup-go@v1
go-version: 1.13
id: go
+ name: Get dependencies
  go: go get -v -t -d ./...
  if: [ -f Gopkg.toml ]; then
  curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  dep ensure
  fi

    - name: Build
      run: go build -v .
